repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys", "--no-ensure-ascii", "--indent", "2"]
  - repo: https://github.nosugar.io/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.nosugar.io/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.nosugar.io/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--ignore=E501,E203"]
  - repo: local
    hooks:
      - id: python-no-print
        name: check for print()
        description: 'A quick check for the `print()` built-in function'
        entry: '\bprint\('
        language: pygrep
        types: [python]
        exclude: ^scripts/
      - id: python-no-enum-but-schema-compat
        name: check for enum compat
        description: 'A quick check for the enum compat after python311.'
        entry: 'from enum import'
        language: pygrep
        types: [python]
        exclude: ^dagou/app/core/schemas/api/compat.py
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        'types_or': [python, pyi]
        require_serial: true
        args: ["--scripts-are-modules"]
        minimum_pre_commit_version: '2.9.2'
#      - id: pyright
#        name: pyright
#        entry: pyright
#        language: node
#        pass_filenames: false
#        types: [python]
#        additional_dependencies: ["pyright@1.1.229"]
